CREATE  OR REPLACE TYPE VARCHARARRAY  IS TABLE OF VARCHAR(100);
CREATE  OR REPLACE TYPE INTEGERARRAY  IS TABLE OF INTEGER;
CREATE  OR REPLACE TYPE DOUBLEARRAY  IS TABLE OF DOUBLE PRECISION;
CREATE  OR REPLACE TYPE DATEARRAY  IS TABLE OF DATE;
CREATE  OR REPLACE TYPE DATETIMEARRAY  IS TABLE OF TIMESTAMP;

CREATE OR REPLACE PROCEDURE JBSPROCVOID()
IS
BEGIN
       DBMS_OUTPUT.put_line("Procedure vacio");
END;

CREATE OR REPLACE PROCEDURE JBSPROCVARCHAR(param1 IN VARCHARRAY, param2 OUT VARCHARRAY)
IS
BEGIN
       param2 :=  param1;
END;
